language: node_js
node_js:
  - "16"
addons:
  chrome: stable
  firefox: latest
notifications:
  slack:
    secure: JKzk2sJSbZ9h2PUVWj6KtOAdFbEEnOtv/VZy05pJ2H41xRgUHiGdtMW/vMSeq6XX3IJN8eW2zd0cJTgkFn0ioAlYvID8zRhcvkFHg60QXquoqtp5y65dxjtVz79hefxSo7FO1NhMZBQWE9Tg6R7XkoyTMth62+T9vqOgu2Hms6M=
    if: (branch = main) AND (type = push)
    on_success: change # default: always
script:
  - npm --silent run deploy-set-version -- --buildVersion $TRAVIS_BRANCH.$TRAVIS_BUILD_NUMBER
  - npm --silent run deploy-status -- --status pending --message 'Waiting for build'

  - npm --silent run eslint
  - npm --silent run markdownlint
  - npm --silent run prettier-check

  - npm --silent run build -- --node

  - npm --silent run coverage -- --browsers FirefoxHeadless --webgl-stub --failTaskOnError --suppressPassed

  - npm --silent run make-zip
  - npm pack &> /dev/null

  - npm --silent run build-apps

  - npm --silent run deploy-s3 -- -b cesium-dev -d cesium/$TRAVIS_BRANCH --confirm -c 'no-cache'
  - npm --silent run deploy-status -- --status success --message Deployed

  - npm --silent run test -- --browsers ChromeCI --failTaskOnError --webgl-stub --release --suppressPassed

  # Various Node.js smoke-screen tests
  - node -e "const Cesium = require('./');"
  - NODE_ENV=development node Specs/test.cjs
  - NODE_ENV=production node Specs/test.cjs
  - node Specs/test.mjs

  - npm --silent run cloc
